name: Build and push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: It would be handy to have the code
        uses: actions/checkout@v2
        with:
          repository: finn-no/postgres-operator
          ref: 14-patches

      - name: Get Go or get... well, just get Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.9"

      - name: Become one with the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push. But, like, funnier.
        run: |
          VERSION=$(git describe --tags --always --dirty)
          IMAGE_BASE=ghcr.io/finn-no/postgres-operator-image
          IMAGE_NAME=$IMAGE_BASE:$VERSION
          LATEST=$IMAGE_BASE:latest

          make IMAGE=$IMAGE_BASE docker
          docker tag $IMAGE_NAME $LATEST

          docker push $IMAGE_NAME
          docker push $LATEST
