name: Build and push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: finn-no/postgres-operator
          ref: 14-patches

      - name: Become one with the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          APP_NAME=postgres-operator
          VERSION=$(git describe --tags --always --dirty)
          IMAGE_BASE=ghcr.io/finn-no/$APP_NAME
          IMAGE_NAME=$IMAGE_BASE:$VERSION
          LATEST=$IMAGE_BASE:latest

          make docker
          docker tag registry.opensource.zalan.do/acid/postgres-operator:$VERSION $IMAGE_NAME
          docker tag $IMAGE_NAME $LATEST

          docker push $IMAGE_NAME
          docker push $LATEST
